import DriedRosePetals from "../../Assets/dry_rose_petal.jpg"
import DryRoseFlowers from "../../Assets/dry_red_rose_flower.jpg";
import DryRoseBuds from "../../Assets/dry_red_rose_bud.jpg";
import Licorice from "../../Assets/licorice.jpg"
import Pomegranate from "../../Assets/pomegranate_flower.jpg"
export const products = [
    { title: "Dry Red Rose Petals", description: "Our “Dry Red Rose Petals” are the height of flower elegance, and have been carefully made to keep their natural beauty and scent. These carefully dried petals are beautiful to look at and delicious to eat. Each petal comes from a fine red rose and is carefully picked by hand and air-dried to perfection, making sure that the petals keep their bright color and delicate texture. These petals are full of antioxidants and vitamins.", image: DriedRosePetals, rating: 5.0, price: 500, numReviews: 10 },
    { title: "Dry Red Rose Flowers", description: "Enjoy the timeless beauty of our Dry Red Rose Flowers, which were carefully made to catch the essence of nature’s beauty. These delicate flowers are carefully chosen from the best rose fields and then dried in a way that keeps their bright colour and alluring scent. Our Dry Red Rose Flowers have many health benefits, such as helping you relax and feel less stressed, improving the health of your skin, and making your immune system stronger.", image: DryRoseFlowers, rating: 3.5, price: 500, numReviews: 10 },
    { title: "Dry Red Rose Buds", description: "Our item “Dry Red Rose Buds” is the very definition of class and elegance. These delicate buds are carefully chosen from the most beautiful rose fields and then dried in a way that keeps their natural beauty and scent.", image: DryRoseBuds, rating: 3.5, price: 500, numReviews: 10 },
    { title: "Licorice", description: "Our Licorice Roots Premium Finger Quality comes from the most fertile areas of Southern Europe and Asia, so you can enjoy their high quality. These high-quality licorice roots were chosen because they are all the same and have a strong, natural taste. With a deep brown exterior and a fibrous beige inner that looks like a thin finger, each root has a strong mix of sweetness and mild bitterness, along with pleasant notes of anise and fennel. The Premium Finger Quality Licorice Roots are great for both cooking and medicine.Our Licorice Roots Premium Finger Quality will take your cooking and health practices to the next level with its great taste and healing qualities.", image: Licorice, rating: 4.0, price: 500, numReviews: 10 },
    { title: "Pomegranate Flower", description: "Our Pomegranate Flowers Quality comes from the most fertile areas of Southern Europe and Asia, so you can enjoy their high quality. These high-quality flowers were chosen because they are all the same and have a strong, natural taste. With a deep brown exterior and a fibrous beige inner that looks like a thin finger, each root has a strong mix of sweetness and mild bitterness, along with pleasant notes of anise and fennel. The Premium Finger Quality Licorice Roots are great for both cooking and medicine.Our Licorice Roots Premium Finger Quality will take your cooking and health practices to the next level with its great taste and healing qualities.", image: Pomegranate, rating: 4.0, price: 500, numReviews: 10 },
]